# ═══════════════════════════════════════════════════════════════
# compose.iam.yml — Source of Truth для IAM/Platform контура
#
# Profiles:
#   infra  — edge, postgres, redis, mailpit, keycloak, observability
#   full   — infra + bff, iam-api, keycloak-init
#
# Сети по ADR 3.5:
#   frontend-net, backend-net, db-net, observ-net
#
# Запуск:
#   docker compose -f ops/iam/compose.iam.yml --env-file ops/iam/.env.iam --profile full up -d
# ═══════════════════════════════════════════════════════════════

services:

  # ════════════════════════════════════════
  # EDGE (Nginx) — единственный published port
  # ════════════════════════════════════════
  edge:
    image: nginx:1.28-alpine
    container_name: pm-edge
    ports:
      - "${EDGE_HTTP_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    # НЕ depends_on bff — nginx стартует сам, вернёт 502 если BFF нет
    networks:
      - frontend-net
      - backend-net
    profiles: ["infra", "full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # BFF (.NET)
  # ════════════════════════════════════════
  bff:
    build:
      context: ../../
      dockerfile: src/BFF/PM.BFF/Dockerfile
    image: pm-bff:dev
    container_name: pm-bff
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Otel__ServiceName: pm-bff
      Otel__Endpoint: "http://otel-collector:4317"
      ConnectionStrings__Redis: "redis:6379,password=${REDIS_PASSWORD}"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend-net
    profiles: ["full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # IAM API (.NET)
  # ════════════════════════════════════════
  iam-api:
    build:
      context: ../../
      dockerfile: src/IAM/PM.IAM.Api/Dockerfile
    image: pm-iam-api:dev
    container_name: pm-iam-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Otel__ServiceName: pm-iam-api
      Otel__Endpoint: "http://otel-collector:4317"
      ConnectionStrings__Redis: "redis:6379,password=${REDIS_PASSWORD}"
      ConnectionStrings__Postgres: "Host=postgres-iam;Port=5432;Database=${IAM_PG_DB};Username=${IAM_PG_USER};Password=${IAM_PG_PASSWORD}"
    depends_on:
      postgres-iam:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend-net
      - db-net
    profiles: ["full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # POSTGRES IAM
  # ════════════════════════════════════════
  postgres-iam:
    image: ${POSTGRES_IMAGE}
    container_name: pm-postgres-iam
    environment:
      POSTGRES_DB: ${IAM_PG_DB}
      POSTGRES_USER: ${IAM_PG_USER}
      POSTGRES_PASSWORD: ${IAM_PG_PASSWORD}
    volumes:
      - iam_pgdata:/var/lib/postgresql    # Postgres 18: НЕ /data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${IAM_PG_USER} -d ${IAM_PG_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - db-net
    profiles: ["infra", "full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # POSTGRES KEYCLOAK
  # ════════════════════════════════════════
  postgres-kc:
    image: ${POSTGRES_IMAGE}
    container_name: pm-postgres-kc
    environment:
      POSTGRES_DB: ${KC_PG_DB}
      POSTGRES_USER: ${KC_PG_USER}
      POSTGRES_PASSWORD: ${KC_PG_PASSWORD}
    volumes:
      - kc_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_PG_USER} -d ${KC_PG_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - db-net
    profiles: ["infra", "full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # REDIS
  # ════════════════════════════════════════
  redis:
    image: ${REDIS_IMAGE}
    container_name: pm-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - backend-net
    profiles: ["infra", "full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # MAILPIT (dev SMTP + Web UI)
  # ════════════════════════════════════════
  mailpit:
    image: ${MAILPIT_IMAGE}
    container_name: pm-mailpit
    ports:
      - "${MAILPIT_WEB_PORT}:8025"
      - "${MAILPIT_SMTP_PORT}:1025"
    networks:
      - backend-net
    profiles: ["infra", "full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # KEYCLOAK — НИКАКИХ ports наружу
  # ════════════════════════════════════════
  keycloak:
    image: ${KEYCLOAK_IMAGE}
    container_name: pm-keycloak
    command: ["start-dev", "--http-port=8080", "--hostname-strict=false"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres-kc:5432/${KC_PG_DB}"
      KC_DB_USERNAME: ${KC_PG_USER}
      KC_DB_PASSWORD: ${KC_PG_PASSWORD}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_MAIL_HOST: mailpit
      KC_MAIL_PORT: "1025"
      # Frontend URL — публичный домен для action links (BFF proxy в Фазе 3)
      KC_HOSTNAME: "http://localhost:${EDGE_HTTP_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '\"status\":\"UP\"'"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    depends_on:
      postgres-kc:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - backend-net
      - db-net
    profiles: ["infra", "full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # KEYCLOAK-INIT (one-shot provisioning)
  # ════════════════════════════════════════
  keycloak-init:
    image: ${KEYCLOAK_CONFIG_CLI_IMAGE}
    container_name: pm-keycloak-init
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "60s"
      IMPORT_FILES_LOCATIONS: "/config/*"
    volumes:
      - ./keycloak/realm-pmplatform.json:/config/realm-pmplatform.json:ro
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - backend-net
    profiles: ["full"]
    restart: "no"

  # ════════════════════════════════════════
  # OBSERVABILITY — OTel Collector
  # ════════════════════════════════════════
  otel-collector:
    image: ${OTEL_COLLECTOR_IMAGE}
    container_name: pm-otel-collector
    volumes:
      - ./observability/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    networks:
      - backend-net
      - observ-net
    profiles: ["infra", "full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # OBSERVABILITY — Elasticsearch
  # ════════════════════════════════════════
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    container_name: pm-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - observ-net
    profiles: ["infra", "full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # OBSERVABILITY — Kibana
  # ════════════════════════════════════════
  kibana:
    image: ${KIBANA_IMAGE}
    container_name: pm-kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      XPACK_SECURITY_ENABLED: "false"
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - observ-net
      - frontend-net
    profiles: ["infra", "full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # OBSERVABILITY — Kibana init (saved objects)
  # ════════════════════════════════════════
  kibana-init:
    image: curlimages/curl:8.5.0
    container_name: pm-kibana-init
    depends_on:
      kibana:
        condition: service_started
    volumes:
      - ./observability/kibana/saved-objects.ndjson:/tmp/saved-objects.ndjson:ro
      - ./observability/kibana/init.sh:/tmp/init.sh:ro
    entrypoint: ["sh", "/tmp/init.sh"]
    networks:
      - observ-net
    profiles: ["infra", "full"]
    restart: "no"

  # ════════════════════════════════════════
  # OBSERVABILITY — Prometheus
  # ════════════════════════════════════════
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: pm-prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - observ-net
      - backend-net
    profiles: ["infra", "full"]
    restart: unless-stopped

  # ════════════════════════════════════════
  # OBSERVABILITY — Grafana
  # ════════════════════════════════════════
  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: pm-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
      - elasticsearch
    networks:
      - observ-net
      - frontend-net
    profiles: ["infra", "full"]
    restart: unless-stopped

# ════════════════════════════════════════
# NETWORKS (ADR 3.5 — 4 сети)
# ════════════════════════════════════════
networks:
  frontend-net:
  backend-net:
  db-net:
  observ-net:

# ════════════════════════════════════════
# VOLUMES
# ════════════════════════════════════════
volumes:
  iam_pgdata:
  kc_pgdata:
  es_data:
  prom_data:
  grafana_data:
