# ═══════════════════════════════════════════════════════════════
# compose.iam.dev.yml — Dev overlay
#
# Использование:
#   docker compose -f ops/iam/compose.iam.yml -f ops/iam/compose.iam.dev.yml \
#     --env-file ops/iam/.env.iam --profile full up -d
#
# Что добавляет:
#   - build target: dev (dotnet watch / hot reload)
#   - volume mounts для исходников
#   - опубликованные порты Postgres/Redis (для отладки через IDE)
#   - nuget_cache volume
# ═══════════════════════════════════════════════════════════════

services:

  bff:
    build:
      target: dev
    volumes:
      - ../../src:/src/src:ro
      - ../../PMPlatform.slnx:/src/PMPlatform.slnx:ro
      - ../../Directory.Build.props:/src/Directory.Build.props:ro
      - nuget_cache:/root/.nuget/packages

  iam-api:
    build:
      target: dev
    volumes:
      - ../../src:/src/src:ro
      - ../../PMPlatform.slnx:/src/PMPlatform.slnx:ro
      - ../../Directory.Build.props:/src/Directory.Build.props:ro
      - nuget_cache:/root/.nuget/packages

  # Debug ports — только для dev
  postgres-iam:
    ports:
      - "${IAM_PG_PORT}:5432"

  postgres-kc:
    ports:
      - "${KC_PG_PORT}:5432"

  redis:
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  nuget_cache:
