services:
  edge:
    image: nginx:1.28-alpine
    ports:
      - "${EDGE_HTTP_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - bff
    networks:
      - frontend
      - backend
    restart: unless-stopped

  # bff и iam-api добавим в A1 override-файле

  postgres-iam:
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_DB: ${IAM_PG_DB}
      POSTGRES_USER: ${IAM_PG_USER}
      POSTGRES_PASSWORD: ${IAM_PG_PASSWORD}
    ports:
      - "${IAM_PG_PORT}:5432"
    volumes:
      - iam_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${IAM_PG_USER} -d ${IAM_PG_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - db
    restart: unless-stopped

  postgres-kc:
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_DB: ${KC_PG_DB}
      POSTGRES_USER: ${KC_PG_USER}
      POSTGRES_PASSWORD: ${KC_PG_PASSWORD}
    ports:
      - "${KC_PG_PORT}:5432"
    volumes:
      - kc_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_PG_USER} -d ${KC_PG_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - db
    restart: unless-stopped

  redis:
    image: ${REDIS_IMAGE}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - backend
    restart: unless-stopped

  mailpit:
    image: ${MAILPIT_IMAGE}
    ports:
      - "${MAILPIT_WEB_PORT}:8025"
      - "${MAILPIT_SMTP_PORT}:1025"
    networks:
      - backend
    restart: unless-stopped

  keycloak:
    image: ${KEYCLOAK_IMAGE}
    command: ["start-dev", "--http-port=8080", "--hostname-strict=false"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres-kc:5432/${KC_PG_DB}"
      KC_DB_USERNAME: ${KC_PG_USER}
      KC_DB_PASSWORD: ${KC_PG_PASSWORD}

      KC_MAIL_HOST: mailpit
      KC_MAIL_PORT: "1025"
    depends_on:
      postgres-kc:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - backend
      - db
    # ВАЖНО: никаких ports наружу (Keycloak не торчит)
    restart: unless-stopped

networks:
  frontend:
  backend:
  db:

volumes:
  iam_pgdata:
  kc_pgdata:
